#配置数据库连接信息
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zhizhen.test.springboot_mybatis.model

#showSql
logging:
  level:
    com:
      example:
        mapper: debug