#配置数据库连接信息
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

#showSql
logging:
  level:
    com:
      example:
        mapper: debug

mybatis:
  #对应mapper映射xml文件所在路径
  mapper-locations: classpath:mapper/*.xml
  #对应实体类路径
  type-aliases-package: com.zhizhen.test.springboot_mybatis.model